### ISSUE TITLE
File Name Conflicts Not Handled

### ISSUE THREAD

**Issue by XinghaiStar** [CNMengHan/QuietDirTozipFile#1]
The code will create the `.zip` file without checking if a file with the same name already exists. If such a file exists, it will be overwritten without any warning ( Suggestion check if the target file already exists before creating the archive to avoid overwriting existing files!
`
   if os.path.exists(zip_file):
       print(f"{zip_file} already exists.")
       return
`

**Comment by XinghaiStar** [comment]
I submitted a new version ❤

**Comment by CNMengHan** [comment]
Thanks for your contribution ❤
